baseURL = "https://olivier5741.github.io/australia/"
languageCode = "fr-be"
title = "Rossana & Olivier in Australia"
theme = "hestia-pure"

[author]
 author = 'Olivier & Rossana'
 profile = 'Backpackers'

[Params]
 localeOgp = "fr-be"