baseURL = "https://rokiwi.github.io/"
title = "Rossana & Olivier en ..."
languageCode = "fr-be"
defaultContentLanguage = "fr"
theme = "rokiwi-pure"
copyright = "2018 Rossana & Olivier in ... powered by Hugo and hosted on Github."
summaryLength = 10
googleAnalytics = "UA-57281931-1"
metaDataFormat = "yaml"

[author]
 author = 'Olivier & Rossana'
 profile = 'Backpackers'
 image = 'favicon.png'

[blackfriday]
 smartypants = false # https://discourse.gohugo.io/t/content-render-character-issue-sample-rsquo/14899/2

[params]
 localeOgp = "fr-be"

[languages]

[languages.fr]
 weight = 1
 languageName = "Français"

[languages.en]
 weight = 2
 languageName = "English" 
 title = "Rossana & Olivier in ..."

