baseURL = "https://olivier5741.github.io/australia/"
languageCode = "fr-be"
title = "Rossana & Olivier in Australia"
theme = "rokiwi-pure"

[author]
 author = 'Olivier & Rossana'
 profile = 'Backpackers'
 image = 'favicon.png'

[Params]
 localeOgp = "fr-be"